name: Python package

on: [push, pull_request]

env:
  POETRY_VERSION: "1.2.2"
  PYTHON_VERSION: "3.10"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry==${POETRY_VERSION}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: poetry

    - name: Install dependencies
      run: poetry install --no-root

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --show-source --max-line-length=127 --statistics --output-file=flake8-${{ matrix.python-version }}.txt

    - name: Check security vulnerabilities with bandit
      run: |
        # run bandit on src
        poetry run bandit -r src -o bandit_src_report.out
        # run bandit on tests, skip the assertion vulnerability
        poetry run bandit -r tests --skip B101 -o bandit_tests_report.out
      continue-on-error: true
      if: ${{ always() }}


    - name: Test with pytest
      run: >
        poetry run pytest tests 
        --doctest-modules 
        --junitxml=junit/test-results-${{ matrix.python-version }}.xml 
        --cov=fastapi_template_project 
        --cov-report=xml 
        --cov-report=html

    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
      
    - name: Upload bandit source code check results
      uses: actions/upload-artifact@v3
      with:
        name: bandit_src_report.out-${{ matrix.python-version }}
        path: bandit_src_report.out

    - name: Upload bandit tests check results
      uses: actions/upload-artifact@v3
      with:
        name: bandit_tests_report-${{ matrix.python-version }}
        path: bandit_tests_report.out
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - name: Upload flake8 check results
      uses: actions/upload-artifact@v3
      with:
        name: flake8-${{ matrix.python-version }}.txt
        path: flake8_report.out
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}